default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root #<%= ENV['MEAT_TONGUE_DB_USER'] %>
  password: rootroot #<%= ENV['MEAT_TONGUE_DB_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: meat_tongue_development

test:
  <<: *default
  database: meat_tongue_test

production:
  <<: *default
  url: <%= ENV['MEAT_TONGUE_DB_URL'] %>
  database: <%= ENV['MEAT_TONGUE_DB'] %>
